services:
  tasks-service:
    build:
      target: test
    image: tasks-service:test

  stats-service:
    build:
      target: test
    image: stats-service:test

  frontend:
    build:
      target: test
    image: frontend:test