# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  SERVICES: tasks-service stats-service frontend
  NODE_SERVICES: tasks-service stats-service
  REGISTRY: localhost:5000
  DOCKER_TAG: latest

dotenv: ['.env']

tasks:
  default:
    desc: Affiche les tâches disponibles
    cmds:
      - task --list
    silent: true

    # Installer soit comme ça mais ce n'est pas simultané, le mieux ici comme il n'y a que 3 services,
    # c'est de faire 3 petit install et un global qui dépend des autres
#  install:
#    desc: Installe les dépendances de tous les services
#    cmds:
#      - echo "Installation des dépendances..."
#      - cd tasks-service && npm i
#      - cd stats-service && npm i
#      - cd frontend && npm i
#      - echo "Dépendances installés"


  bump:
    cmds:
      - |
        v=$(grep VERSION .env | cut -d '=' -f2)
        v=$((v+1))
        echo "VERSION=$v" > .env
        echo "Nouvelle version: $v"

    # Quand beaucoup de services, installer via boucle for, pas simultané
  install:
    desc: Installe les dépendances de tous les services
    deps: [clean]
    cmds:
      - for: { var: NODE_SERVICES, split: ' ' }
        cmd: |
          echo "Installation de {{.ITEM}}..."
          cd {{.ITEM}} && npm i
      - echo "Dépendances installés"

  test:
    desc: Lancement des tests des services back
    deps: [install]
    cmds:
      - for: { var: NODE_SERVICES, split: ' ' }
        cmd: |
          echo "Lancement des tests pour {{.ITEM}}..."
          cd {{.ITEM}} && npm run test
      - echo "Tests terminés"

  clean:
    desc: Nettoie les dossiers node_modules et dist
    cmds:
      - for: { var: NODE_SERVICES, split: ' ' }
        cmd: |
          echo "Lancement du clean pour {{.ITEM}}..."
          rm -rf {{.ITEM}}/node_modules  {{.ITEM}}/dist
      - echo "Clean terminé"

  build:compose:
    desc: Build les images de prod avec docker compose (pas l'override)
    deps: [bump]
    cmds:
      - docker compose -f docker-compose.prod.yml build --parallel

  build:compose:service:
  desc: Build un service spécifique avec docker compose
  deps: [bump]
  cmds:
    - echo "Build de {{.CLI_ARGS}}..."
    - docker compose build {{.CLI_ARGS}}

  test:services:
    desc: Tester un service spécifique
    cmds:
      - echo "Test de {{.CLI_ARGS}}..."
      - cd {{.CLI_ARGS}} && npm test

  tag:
    deps: [build:compose]
    desc: Tag un service
    cmds :
      - for: { var: SERVICES, split: ' ' }
        cmd: |
          echo "Tag de {{.ITEM}}..."
          docker tag {{.ITEM}}:{{.VERSION}} {{.REGISTRY}}/{{.ITEM}}:{{.VERSION}}
          docker tag {{.ITEM}}:{{.VERSION}} {{.REGISTRY}}/{{.ITEM}}:{{.DOCKER_TAG}}
      - echo "Tags terminés"

  push:
    deps: [tag]
    desc: Push un service sur le registry
    cmds:
      - for: { var: SERVICES, split: ' ' }
        cmd: |
          echo "Push de {{.ITEM}}..."
          docker push {{.REGISTRY}}/{{.ITEM}}:{{.VERSION}}
          docker push {{.REGISTRY}}/{{.ITEM}}:{{.DOCKER_TAG}}
      - echo "Pushs terminés"
